services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./database/DML.sql:/docker-entrypoint-initdb.d/DML.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres